Livermore 1.3 Update
wuhaotian1007/Livermore_quantitative_trading pull request #5
Opened 2021-08-16 12:03 UTC by wuhaotian1007

**CONTENT**
- 1.It includes new report structure and new integration functions, and further encapsulates the code to improve the callability.
- 2.Add new trend signal:"Aug Danger"

**TEST CASE**
- 1.Compared with the report of version 1.2, the trend signal content is correct
[XAUUSD_TNX_DXY_total.xlsx](https://github.com/wuhaotian1007/Livermore_quantitative_trading/files/6992128/XAUUSD_TNX_DXY_total.xlsx)
- 2.There is a difference in the time processing method between the profit margin calculation part and the profit margin calculation module. This time, the closing date is taken as the deadline. The first time of each period is selected as the test object for various profit margins, and the human flesh calculation and report are correct.

2021-08-16 12:53 UTC, jewforice commented
1、把利润率计算详表里的利润率也改成按平仓日计算，然后再和行情记录整合利润率显示的表都对比一次。
2、pr的描述都改成用中文
3、新表和旧表都保持同时生成，直到我对比过策略的数据后确认可以把旧行情记录表停掉以后再停。

2021-08-16 12:56 UTC, jewforice requested changes
1、把利润率计算详表里的利润率也改成按平仓日计算，然后再和行情记录整合利润率显示的表都对比一次。
2、pr的描述都改成用中文
3、新表和旧表都保持同时生成，直到我对比过策略的数据后确认可以把旧行情记录表停掉以后再停。

2021-08-17 03:28 UTC, jewforice commented on Livermore1.3/launcher.py
> +db_Path = "C:\\Users\\sgnjim\\Desktop\\for_python\\Livermore1.3\\database"
怎么又有绝对路径了？改成相对路径

2021-08-17 03:30 UTC, jewforice commented on Livermore1.3/launcher.py
> +trading_history_input_path = r"C:\Users\sgnjim\OneDrive\work\Trading_history\交易历史输入.xlsx"
绝对路径*2

2021-08-17 03:36 UTC, jewforice commented on Livermore1.3/launcher.py
> +trading_history_input_path = r"C:\Users\sgnjim\OneDrive\work\Trading_history\交易历史输入.xlsx"
绝对路径*3

2021-08-17 03:36 UTC, jewforice commented on Livermore1.3/launcher.py
> +his_output_xlsx_path_cloud = r"C:\Users\sgnjim\OneDrive\work\Trading_history\trade_history.xlsx"
绝对路径*4

2021-08-17 03:37 UTC, jewforice commented on Livermore1.3/launcher.py
> +# 删除文件函数
为什么要删除db文件？

2021-08-17 03:42 UTC, jewforice commented on Livermore1.3/launcher.py
> +    comb("XAUUSD", 3/7, database_path, 600, DXY=- 3/0.3, TNX=- 3/0.03)
这个是干啥的？

2021-08-17 03:42 UTC, jewforice commented on Livermore1.3/launcher.py
> +launcher("down")
down这个参数是什么意思？

2021-08-17 03:49 UTC, jewforice commented on Livermore1.3/lib/cal_of_trading_inf/category.py
> +        add_new_currency("XAUUSD", 0.5, 500, 100, 4500, 0.01)
这个后续应该弄成是从excel表里面读入，要不改个参数你还得改代码

2021-08-17 03:50 UTC, jewforice commented on Livermore1.3/lib/cal_of_trading_inf/category.py
> +        add_new_currency("XAUUSD", 0.5, 500, 100, 4500, 0.01)
这个在搞策略模拟的时候改掉吧

2021-08-17 03:58 UTC, jewforice commented on Livermore1.3/lib/est_trend/default_downtrend.py
> +                                        if last_column == 2:
建议可以把if换成case-switch，后续如果有新增信号时会更方便

2021-08-17 04:01 UTC, jewforice commented on Livermore1.3/lib/est_trend/default_downtrend.py
> +                            "update COMB_TREND set AUG = {0} where ID = {1}".format(Aug_danger, ID))
八月平仓预警是作为独立一个信号来存储的吧？

2021-08-17 10:51 UTC, jewforice commented on Livermore1.3/lib/standardization_storage/XAUUSD_std.py
> +        DXY_data_path = 'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/raw_data/DXY.csv'
改为相对路径

2021-08-17 10:51 UTC, jewforice commented on Livermore1.3/lib/standardization_storage/XAUUSD_std.py
> +            'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/database/XAUUSD.db')
改为相对路径

2021-08-17 10:52 UTC, jewforice commented on Livermore1.3/lib/visualization/downtrend_vis_2.py
> +    'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/database/XAUUSD_DXY.db')
改成相对路径

2021-08-17 10:54 UTC, jewforice commented on Livermore1.3/lib/visualization/downtrend_vis_2.py
> +xl.save('C:/Users/sgnjim/Desktop/for_python/Livermore1.3/report/XAUUSD-DXY-{0}-downtrend.xls'.format(
改成相对路径

2021-08-17 10:54 UTC, jewforice commented on Livermore1.3/lib/visualization/downtrend_vis_3.py
> +    'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/database/XAUUSD_TNX.db')
改成相对路径

2021-08-17 10:55 UTC, jewforice commented on Livermore1.3/lib/visualization/downtrend_vis_3.py
> +xl.save('C:/Users/sgnjim/Desktop/for_python/Livermore1.3/report/XAUUSD-TNX-{0}-downtrend.xls'.format(
改成相对路径

2021-08-17 11:00 UTC, jewforice commented on Livermore_cal_of_profit_margin/launcher.py
> +trading_history_input_path = r"C:\Users\sgnjim\OneDrive\work\Trading_history\交易历史输入.xlsx"
改成相对路径

2021-08-17 11:05 UTC, jewforice requested changes
请按评论修改，主要是路径

2021-08-18 03:12 UTC, wuhaotian1007 commented on Livermore1.3/launcher.py
> +# 删除文件函数
db文件中文件名唯一，并且有唯一的key时间

2021-08-18 03:12 UTC, wuhaotian1007 commented on Livermore1.3/launcher.py
> +his_output_xlsx_path_cloud = r"C:\Users\sgnjim\OneDrive\work\Trading_history\trade_history.xlsx"
done

2021-08-18 03:12 UTC, wuhaotian1007 commented on Livermore1.3/launcher.py
> +trading_history_input_path = r"C:\Users\sgnjim\OneDrive\work\Trading_history\交易历史输入.xlsx"
done

2021-08-18 03:12 UTC, wuhaotian1007 commented on Livermore1.3/launcher.py
> +db_Path = "C:\\Users\\sgnjim\\Desktop\\for_python\\Livermore1.3\\database"
done

2021-08-18 03:13 UTC, wuhaotian1007 commented on Livermore1.3/launcher.py
> +    comb("XAUUSD", 3/7, database_path, 600, DXY=- 3/0.3, TNX=- 3/0.03)
已注释，用于生成组合价格

2021-08-18 03:13 UTC, wuhaotian1007 commented on Livermore1.3/launcher.py
> +launcher("down")
已注释，默认趋势

2021-08-18 03:14 UTC, wuhaotian1007 commented on Livermore1.3/lib/est_trend/default_downtrend.py
> +                            "update COMB_TREND set AUG = {0} where ID = {1}".format(Aug_danger, ID))
db中单独一列AUG，1为危险，默认为None

2021-08-18 03:15 UTC, wuhaotian1007 commented on Livermore1.3/lib/standardization_storage/XAUUSD_std.py
> +        DXY_data_path = 'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/raw_data/DXY.csv'
done

2021-08-18 03:16 UTC, wuhaotian1007 commented on Livermore1.3/lib/standardization_storage/XAUUSD_std.py
> +            'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/database/XAUUSD.db')
down

2021-08-18 03:17 UTC, wuhaotian1007 commented on Livermore1.3/lib/visualization/downtrend_vis_2.py
> +    'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/database/XAUUSD_DXY.db')
弃用py已删除

2021-08-18 03:18 UTC, wuhaotian1007 commented on Livermore1.3/lib/visualization/downtrend_vis_2.py
> +xl.save('C:/Users/sgnjim/Desktop/for_python/Livermore1.3/report/XAUUSD-DXY-{0}-downtrend.xls'.format(
弃用py已删除

2021-08-18 03:18 UTC, wuhaotian1007 commented on Livermore1.3/lib/visualization/downtrend_vis_3.py
> +    'C:/Users/sgnjim/Desktop/for_python/Livermore1.3/database/XAUUSD_TNX.db')
弃用py已删除

2021-08-18 03:18 UTC, wuhaotian1007 commented on Livermore1.3/lib/visualization/downtrend_vis_3.py
> +xl.save('C:/Users/sgnjim/Desktop/for_python/Livermore1.3/report/XAUUSD-TNX-{0}-downtrend.xls'.format(
弃用py已删除

2021-08-18 08:09 UTC, wuhaotian1007 commented
已更新文件

2021-08-18 09:55 UTC, jewforice approved these changes
review完毕，请release

2021-08-18 09:55 UTC, merged